name: record_android
description: Android specific implementation for record package called by record_platform_interface.
version: 1.0.3
publish_to: none
homepage: https://github.com/llfbandit/record/tree/master/record_android

environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.13.1"

dependencies:
  flutter:
    sdk: flutter

  record_platform_interface:
    git: https://github.com/kumsumit/record_platform_interface.git

flutter:
  plugin:
    implements: record
    platforms:
      android:
        package: com.llfbandit.record
        pluginClass: RecordPlugin
